launch_image_cropper:
  ros__parameters:
    image_path: "senai_ros2/images/img.jpg"
    output_path: "senai_ros2/images/img_cropped.jpg"
    
launch_image_receiver:
  ros__parameters:
    save_directory: "senai_ros2/images/"
    request_amounts: 5
